### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by AndrewSB** [AndrewSB/iOS-cupcake-point-of-sale#1]
![ios simulator screen shot nov 1 2014 7 41 27 pm](https://cloud.githubusercontent.com/assets/3814772/4874069/e99654cc-6239-11e4-9685-ab436f9bbb37.png)

**Comment by rohitbsehgal** [comment]
the answer is $3.00, because as you can see the first cupcake is white. So naturally it is given a higher value than the second cupcake, which is brown. And so the first one is $1.00 and the second one is $0.75. And the third one is even more expensive, because whoever created the prices is anti lgbt, and is trying to make rainbow cost more. This is racist and anti lgbt. This is an outrage.

**Comment by AndrewSB** [comment]
I applaud you sir
